// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations use the DIRECT (non-pooled) connection. The app runtime uses
    // the pooled DATABASE_URL via the driver adapter in lib/prisma.ts.
    //
    // Read via process.env (not the strict env() helper) so `prisma generate`
    // succeeds on Vercel, where only DATABASE_URL is set — generate doesn't need
    // a datasource URL, and locally dotenv populates DIRECT_URL for migrations.
    url: process.env.DIRECT_URL,
  },
});
