// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations use the DIRECT (non-pooled) connection. The app runtime uses
    // the pooled DATABASE_URL via the driver adapter in lib/prisma.ts.
    url: env("DIRECT_URL"),
  },
});
